export interface Product {
    id: string;
    name: string;
    brand: string;
    description: string;
    price: number;
    sizes: number[];
    category: "WOMEN" | "MEN" | "UNISEX" | "GIFT_SET" | "NICHE";
    scentFamily: string;
    topNotes: string;
    middleNotes: string;
    baseNotes: string;
    modelUrl?: string;
    boxModelUrl?: string;
}

export const products: Product[] = [
    {
        id: "1",
        name: "Aventus",
        brand: "Creed",
        description: "The exceptional Aventus was inspired by the dramatic life of a historic emperor, celebrating strength, power and success. Introduced in 2010 and crafted by the deft hand of Master Perfumer Olivier Creed, this scent has grown to become the best-selling fragrance in the history of the brand.",
        price: 495,
        sizes: [30, 50, 100],
        category: "MEN",
        scentFamily: "FRUITY",
        topNotes: "Pineapple, Bergamot, Blackcurrant Leaves, Apple",
        middleNotes: "Birch, Pink Berries, Patchouli, Jasmine",
        baseNotes: "Musk, Oakmoss, Ambergris, Vanilla",
        modelUrl: "/models/CreedAventus/aventus.glb",
        boxModelUrl: "/models/CreedAventus/aventusBox.glb",
    },
    {
        id: "2",
        name: "Bleu de Chanel",
        brand: "Chanel",
        description: "A tribute to masculine freedom in an aromatic-woody fragrance with a captivating trail. A timeless, scent housed in a bottle of deep and mysterious blue. BLEU DE CHANEL Parfum is an accomplished composition with a pure, deep character. An intensely masculine signature that denotes self-confidence.",
        price: 155,
        sizes: [50, 100, 150],
        category: "MEN",
        scentFamily: "WOODY",
        topNotes: "Lemon Zest, Bergamot, Mint, Artemisia",
        middleNotes: "Lavender, Geranium, Green Notes, Pineapple",
        baseNotes: "Sandalwood, Cedar, Amberwood, Tonka Bean, Iso E Super",
        modelUrl: "/models/BleudeChannel/bleu.glb",
        boxModelUrl: "/models/BleudeChannel/bleuBox.glb",
    },
    {
        id: "3",
        name: "Sauvage",
        brand: "Dior",
        description: "A radically fresh composition, dictated by a name that has the ring of a manifesto. Raw and noble all at once. Radiant top notes burst with the juicy freshness of Reggio di Calabria Bergamot. Ambroxan, derived from precious ambergris, unleashes a powerfully woody trail.",
        price: 145,
        sizes: [60, 100, 200],
        category: "MEN",
        scentFamily: "AROMATIC WOODY",
        topNotes: "Calabrian Bergamot, Pepper",
        middleNotes: "Sichuan Pepper, Lavender, Patchouli",
        baseNotes: "Ambroxan, Cedar, Labdanum",
        modelUrl: "/models/DiorSauvage/sauvage_perfume.glb",
        boxModelUrl: "/models/DiorSauvage/sauvageBox.glb",
    },
    {
        id: "4",
        name: "Hugo Man",
        brand: "Hugo Boss",
        description: "An iconic fragrance for the man who pushes the boundaries. Fresh, bold, and masculine. Features crisp green apple and vibrant herbal notes.",
        price: 95,
        sizes: [75, 125, 200],
        category: "MEN",
        scentFamily: "AROMATIC GREEN",
        topNotes: "Green Apple, Mint, Lavender, Grapefruit",
        middleNotes: "Sage, Geranium, Carnation, Jasmine",
        baseNotes: "Fir, Cedar, Patchouli",
        modelUrl: "/models/Hugo/hugo_bottle.glb",
        boxModelUrl: "/models/Hugo/hugo_box.glb",
    },
    {
        id: "5",
        name: "Hugo Woman",
        brand: "Hugo Boss",
        description: "A fruity, floral fragrance with an unexpected boyish twist. Blends naturally sourced ingredients with innovative molecules.",
        price: 85,
        sizes: [50, 75, 125],
        category: "WOMEN",
        scentFamily: "FLORAL FRUITY",
        topNotes: "Boysenberry, Italian Mandarin, Grass",
        middleNotes: "Jasmine, Black Tea, Plum, Iris",
        baseNotes: "Amber, Sandalwood, Cedar",
        modelUrl: "/models/Hugo/hugo_woman_bottle.glb",
        boxModelUrl: "/models/Hugo/hugo_woman_box.glb",
    },
    {
        id: "6",
        name: "Addict",
        brand: "Dior",
        description: "Dior Addict is a floral-oriental fragrance with a passionate and intuitive personality. The head note features the Silk Tree Flower, Mandarin Leaf and Orange Blossom. The heart note is the Queen of the Night, a rare flower that blooms only for a few hours. The base note is Bourbon Vanilla.",
        price: 130,
        sizes: [30, 50, 100],
        category: "WOMEN",
        scentFamily: "ORIENTAL FLORAL",
        topNotes: "Silk Tree Flower, Mandarin Leaf, Orange Blossom",
        middleNotes: "Queen of the Night Flower, Rose, Jasmine",
        baseNotes: "Bourbon Vanilla, Sandalwood, Tonka Bean",
        modelUrl: "/models/DiorAdict/diorAdict.glb",
    },
    {
        id: "7",
        name: "Code Parfum",
        brand: "Armani",
        description: "Strong yet sensitive, Armani Code Parfum reinvents the olfactory signature of the original Armani Code fragrance. Retaining its woody aromatic, sensual identity, Armani Code Parfum captures the Armani Code essence. This is expressed in the fragrance's aromatic top notes and powerfully masculine base notes.",
        price: 145,
        sizes: [50, 75, 125],
        category: "MEN",
        scentFamily: "WOODY AROMATIC",
        topNotes: "Bergamot, Bergamot Leaf",
        middleNotes: "Iris, Orris, Salvia, Aldehydes",
        baseNotes: "Tonka Bean, Cedar",
        modelUrl: "/models/ArmaniCode/armani_code_parfum_125ml.glb",
    },
    {
        id: "8",
        name: "Wanted By Night",
        brand: "Azzaro",
        description: "Azzaro Wanted by Night is the fragrance of a modern-day Gatsby. An extraordinary man. Elegant, bold, mysterious, he is surrounded by an air of confidence and power. Whether night or day, he attracts and arouses desire... For him, it’s an endless night; and for them, it’s a one-on-one moment that they will never forget.",
        price: 115,
        sizes: [50, 100],
        category: "MEN",
        scentFamily: "WOODY SPICY",
        topNotes: "Cinnamon, Mandarin Orange, Lavender, Lemon",
        middleNotes: "Fruity Notes, Incense, Red Cedar, Cumin",
        baseNotes: "Tobacco, Vanilla, Leather, Benzoin, Iso E Super, Cypress, Patchouli",
        modelUrl: "/models/AzzaroWantedByNight/azzaro_wanted_by_night.glb",
    },
    {
        id: "9",
        name: "Allure Homme Sport Eau Extreme",
        brand: "Chanel",
        description: "A powerful, dynamic fragrance that pushes boundaries. An aromatic musk with powerful notes that evoke a world of intense experiences and ultimate challenges. The ultimate choice for the man who lives for the adrenaline of the moment.",
        price: 135,
        sizes: [50, 100, 150],
        category: "MEN",
        scentFamily: "WOODY AROMATIC",
        topNotes: "Mandarin Orange, Mint, Cypress, Sage",
        middleNotes: "Pepper",
        baseNotes: "Tonka Bean, Musk, Sandalwood, Cedar",
        modelUrl: "/models/ChanelAllure/chanel_allure_homme_sport_eau_extreme.glb",
    },
    {
        id: "10",
        name: "Acqua di Gio Parfum",
        brand: "Giorgio Armani",
        description: "A new, deep & intense freshness, inspired by the meeting of the sea and the rock. This intense fragrance opens with notes of bergamot and rosemary, revealing a heart of geranium and sage, and settling into a warm, sensual base of patchouli and incense.",
        price: 155,
        sizes: [40, 75, 125],
        category: "MEN",
        scentFamily: "AROMATIC AQUATIC",
        topNotes: "Bergamot, Marine Notes",
        middleNotes: "Rosemary, Geranium, Sage",
        baseNotes: "Patchouli, Incense",
        modelUrl: "/models/GiorgioArmaniADG/giorgio_armani_acqua_di_gio_parfum_125ml.glb",
    },
    {
        id: "11",
        name: "Le Male Elixir",
        brand: "Jean Paul Gaultier",
        description: "A burning fragrance that turns up the heat. Intense, sensual, and masculine. Le Male Elixir is a powerhouse of a scent that blends the freshness of mint with the warmth of benzoin and tonka bean.",
        price: 125,
        sizes: [75, 125],
        category: "MEN",
        scentFamily: "ORIENTAL FOUGERE",
        topNotes: "Lavender, Mint",
        middleNotes: "Vanilla, Benzoin",
        baseNotes: "Honey, Tonka Bean, Tobacco",
        modelUrl: "/models/JPGLeMaleElixir/jean_paul_gaultier_le_male_elixir_75ml.glb",
    },
    {
        id: "12",
        name: "Ultra Male",
        brand: "Jean Paul Gaultier",
        description: "The ultimate rogue. Ultra Male is an intense version of the classic Le Male, with added sweetness and spice. It's a fragrance for the man who is confident and unafraid to stand out.",
        price: 110,
        sizes: [75, 125],
        category: "MEN",
        scentFamily: "ORIENTAL FOUGERE",
        topNotes: "Pear, Lavender, Mint, Bergamot, Lemon",
        middleNotes: "Cinnamon, Caraway, Clary Sage",
        baseNotes: "Black Vanilla Husk, Amber, Patchouli, Cedar",
        modelUrl: "/models/JPGUltraMale/jean_paul_gaultier_ultramale_75ml.glb",
    },
    {
        id: "13",
        name: "Explorer",
        brand: "Montblanc",
        description: "This unconventional woody aromatic leather Eau de Parfum reveals a green fresh Italian Bergamot, contrasted by a powerful Vetiver from Haiti, and combined with rich and exclusive Patchouli from Indonesia. A fragrance that takes you on a journey of discovery.",
        price: 105,
        sizes: [30, 60, 100],
        category: "MEN",
        scentFamily: "WOODY AROMATIC",
        topNotes: "Bergamot, Pink Pepper, Clary Sage",
        middleNotes: "Haitian Vetiver, Leather",
        baseNotes: "Ambroxan, Akigalawood, Indonesian Patchouli Leaf, Cacao Pod",
        modelUrl: "/models/MontblancExplorer/montblanc_explorer.glb",
    },
    {
        id: "14",
        name: "Spicebomb Extreme",
        brand: "Viktor & Rolf",
        description: "An explosive concentrate of masculine sensuality. Spicebomb Extreme is an intense version of the original Spicebomb, with added depth and complexity. It's a fragrance that commands attention.",
        price: 140,
        sizes: [50, 90],
        category: "MEN",
        scentFamily: "ORIENTAL SPICY",
        topNotes: "Black Pepper, Grapefruit",
        middleNotes: "Cumin, Saffron, Lavender",
        baseNotes: "Tobacco, Vanilla, Amber",
        modelUrl: "/models/SpicebombExtreme/viktor__rolf_spicebomb_extreme.glb",
    },
    {
        id: "15",
        name: "Black Platinum",
        brand: "Banana Republic",
        description: "A sophisticated and modern fragrance. Black Platinum is a woody floral musk that evokes elegance and power. Perfect for the contemporary individual who values quality and style.",
        price: 85,
        sizes: [75, 100],
        category: "UNISEX",
        scentFamily: "WOODY FLORAL MUSK",
        topNotes: "Pink Pepper, Lemon, Bergamot",
        middleNotes: "Orange Blossom, Iris, Jasmine",
        baseNotes: "Leather, Moss, Patchouli",
        modelUrl: "/models/BananaRepublic/black_platinum.glb",
    },
    {
        id: "16",
        name: "Coco Mademoiselle",
        brand: "Chanel",
        description: "The essence of a free and bold woman. A feminine oriental fragrance with a strong character and a surprising freshness. Sparks of fresh and vibrant orange immediately awaken the senses.",
        price: 165,
        sizes: [50, 100, 200],
        category: "WOMEN",
        scentFamily: "ORIENTAL FLORAL",
        topNotes: "Orange, Mandarin Orange, Bergamot, Orange Blossom",
        middleNotes: "Turkish Rose, Jasmine, Mimosa, Ylang-Ylang",
        baseNotes: "Patchouli, White Musk, Vanilla, Vetiver, Tonka Bean, Opoponax",
        modelUrl: "/models/CocoMademoiselle/coco_mademoiselle.glb",
    },
    {
        id: "17",
        name: "Rich Man",
        brand: "Paris Bleu",
        description: "A bold and energetic fragrance for the man who knows what he wants. Rich Man combines fresh citrus notes with a spicy heart and a woody base for a lasting impression.",
        price: 45,
        sizes: [100],
        category: "MEN",
        scentFamily: "AROMATIC FOUEGERE",
        topNotes: "Bergamot, Pear, Pink Pepper",
        middleNotes: "Lavender, Sage, Geranium",
        baseNotes: "Cashmeran, Patchouli, Sandalwood",
        modelUrl: "/models/RichMan/rich_man.glb",
    },
    {
        id: "18",
        name: "Oud Wood",
        brand: "Tom Ford",
        description: "One of the most rare, precious, and expensive ingredients in a perfumer's arsenal, oud wood is often burned in incense-filled temples. Exotic rosewood and cardamom give way to a smoky blend of rare oud wood, sandalwood and vetiver.",
        price: 295,
        sizes: [30, 50, 100],
        category: "UNISEX",
        scentFamily: "WOODY",
        topNotes: "Rosewood, Cardamom, Chinese Pepper",
        middleNotes: "Oud Wood, Sandalwood, Vetiver",
        baseNotes: "Tonka Bean, Vanilla, Amber",
        modelUrl: "/models/TomFord/tom_ford.glb",
    },
    {
        id: "19",
        name: "Oud & Hydra",
        brand: "Villain",
        description: "A dark and mysterious duo of fragrances. Oud brings the deep, smoky intensity while Hydra adds a splash of refreshing aquatic energy. A versatile choice for the modern man.",
        price: 65,
        sizes: [100],
        category: "MEN",
        scentFamily: "WOODY AQUATIC",
        topNotes: "Lemon, Mandarin, Marine Notes",
        middleNotes: "Oud, Spices, Lavender",
        baseNotes: "Patchouli, Amber, Cedarwood",
        modelUrl: "/models/Villain/villian_oud_hydra.glb",
    }
];

export const getProductById = (id: string) => products.find(p => p.id === id);
